### ISSUE TITLE
Schedule not returned in GetCrawlers API response

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#219]
Original issue: https://github.com/boto/boto3/issues/3202

'Schedule' is supposed to be returned based on Response Syntax: https://docs.aws.amazon.com/glue/latest/webapi/API_GetCrawlers.html

The GetCrawler API is returning 'Schedule' in the response.

**Comment by tim-finnigan** [comment]
P62024789

**Comment by tim-finnigan** [comment]
We heard back from a member of the team who could reproduce the issue and they created a backlog item to address it it. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for updates on this, or feel free to check back in here.

**Comment by tim-finnigan** [comment]
A member from the service team let me know that a fix has been merged and will soon be deployed.

**Comment by utkarsh079** [comment]
Is there a plan for this? I am still facing this issue with boto3-1.26.64.

**Comment by tim-finnigan** [comment]
Will check in again with service team to see about this, please let us know @utkarsh079 if there are any other details you can share such as the steps to reproduce this.

**Comment by tim-finnigan** [comment]
I just tested again and do see Schedule returned so I believe this is now addressed. If you're still seeing the issue please share the steps to reproduce.
